%% Periventricular Diffusivity (PVeD) Estimation
% 1. This script is designed to estimate the transverse proportion of 
% water diffusivity based on tensor elements in the periventricular areas.

% 2. The script takes reconstructed diffusion tensor images as input. 
% The tensor should be processed using DSI Studio, and requires `.fib.gz` files 
% as input to estimate the PVeD. 
% Please ensure DSI Studio reconstruction has been completed prior to running this script.
% Instructions for tensor reconstruction are available on our GitHub repository.

% 3. Given that the most common DTI acquisition voxel size is 2 mm, 
% the reconstructed tensor image is expected to have a matrix size of 78×94×68. 
% If the image dimensions do not match this size, the script will automatically 
% resize the images to fit these dimensions.
% If you wish to preserve a higher image resolution (e.g., 1 mm), 
% please validate the outputs generated by this script as some hyperparameters 
% were optimized based on the original tensor image size (78×94×68).

% Requirement: MATLAB R2016b and above

% The original environment for the implementation:
% MATLAB R2023a and SPM (v7771)

dir_pkg = '~/project/pkg_pved_est';
addpath(dir_pkg);

%% Load fib files and run the estimation
% specify the package directory
dir_pkg = '~/project/pkg_pved_est';

% specify the fib file directory
dir_fib = '~/project/data';

% estimation
pved_est(dir_fib, dir_pkg);
fprintf('Done!\n');

% The outputs include images generated during the processing steps as well as a CSV table. 

% The table contains a column labeled 'QA_index', which serves as a quality control marker. 
% If this column contains extreme values (e.g. beyond 3 standard deviations), 
% it may indicate potential issues with the estimated PVeD metrics, 
% which could reduce confidence in their accuracy.

% output:
% 1. [fib_name].md.nii: extracted mean diffusivity maps from fib files
% 2. csf_mask_[fib_name].md.nii: segmented CSF masks
% 3. lv_mask_[fib_name].md.nii: estimated lateral ventricle masks
% 4. final_pvs_[fib_name].md.nii: estimated periventricular area masks
% 5. ttr_[fib_name].md.nii: estimated TTR maps
% 6. PVeD_metrics.csv: output table with the estimated metrics
